# Databricks notebook source
# /// script
# [tool.databricks.environment]
# environment_version = "5"
# ///
# MAGIC %md
# MAGIC # 01 · Bronze — ingest SEC EDGAR  (incremental)
# MAGIC
# MAGIC Pulls, per CIK in `config/ciks.json`:
# MAGIC - the Submissions API payload (filing history + metadata)
# MAGIC - the XBRL companyfacts payload (pre-extracted financial facts)
# MAGIC - each referenced primary filing document (HTML) + the full submission `.txt`
# MAGIC
# MAGIC Raw filing bytes land in the `bronze_edgar_raw` **Volume**; metadata / JSON /
# MAGIC extracted text land in `bronze_*` Delta tables. All fetches go through
# MAGIC `lib/sec_client.SecClient` (token bucket ≤ 8 req/s, descriptive User-Agent,
# MAGIC 429/5xx retry). Fetch is **driver-sequential** so the 10 req/s SEC cap is
# MAGIC honored globally without a distributed rate limiter.
# MAGIC
# MAGIC ## Incremental contract
# MAGIC
# MAGIC Every write is a Delta **MERGE**, never an overwrite — a scraping is never
# MAGIC lost, even if a CIK later leaves `config/ciks.json` or drops out of the
# MAGIC submissions window.
# MAGIC
# MAGIC | Table | Key | On match |
# MAGIC |---|---|---|
# MAGIC | `bronze_company_submissions` | `cik` | refresh (filing list changes daily) |
# MAGIC | `bronze_xbrl_facts` | `cik` | refresh (new facts each filing) |
# MAGIC | `bronze_filings` | `cik, accession` | keep original |
# MAGIC | `bronze_filing_documents` | `cik, accession, document` | keep original |
# MAGIC | `bronze_filing_text` | `cik, accession, doc_kind` | keep original |
# MAGIC
# MAGIC - **`mode=incremental`** (default): an accession already in `bronze_filings`
# MAGIC   whose Volume files exist is skipped — no HTTP for the primary doc or `.txt`.
# MAGIC   Only genuinely new filings are fetched.
# MAGIC - **`mode=full`**: re-fetches every in-window filing's documents (repair /
# MAGIC   backfill missing Volume files). Still MERGE — nothing is dropped.

# COMMAND ----------

# DBTITLE 1,Widgets & config
import json
import os
import sys
import datetime as dt

# Make `lib/` importable when run from a Databricks Git folder.
_repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if _repo_root not in sys.path:
    sys.path.insert(0, _repo_root)

from lib.sec_client import SecClient, cik10, accession_nodash, iter_recent_filings

dbutils.widgets.text("catalog", "bootcamp_students")
dbutils.widgets.text("schema", "zdsteele_capstone")
# ../config/ciks.json = pilot (6). ../config/ciks_full.json = scaled universe
# (~470 S&P 500, generated by config/build_universe.py).
dbutils.widgets.text("ciks_config", "../config/ciks.json")
dbutils.widgets.dropdown("mode", "incremental", ["incremental", "full"])
# How many *new* filing documents to download per company per run. XBRL
# companyfacts (the Volume driver — full history per CIK) is fetched regardless,
# so keep this modest for the scaled run (recent filings are all the section /
# chunk / AI-briefing layers need). 12 ≈ ~3 years of 10-K/10-Q/8-K.
dbutils.widgets.text("max_new_filings_per_cik", "12")
# Flush to Delta every N companies so a timeout / failure only loses the current
# batch — the next run reads seen_accessions from bronze_filings and resumes.
dbutils.widgets.text("batch_size", "25")
dbutils.widgets.text(
    "sec_user_agent",
    "EDGAR Intelligence Platform - Zach Steele zacharysteele8@gmail.com",
)

CATALOG = dbutils.widgets.get("catalog")
SCHEMA = dbutils.widgets.get("schema")
MODE = dbutils.widgets.get("mode")
MAX_NEW = int(dbutils.widgets.get("max_new_filings_per_cik"))
BATCH_SIZE = int(dbutils.widgets.get("batch_size"))
USER_AGENT = dbutils.widgets.get("sec_user_agent")
FULL = MODE == "full"

with open(dbutils.widgets.get("ciks_config")) as fh:
    CFG = json.load(fh)
COMPANIES = CFG["companies"]
FORMS = set(CFG.get("forms", ["10-K", "10-Q", "8-K"]))

VOLUME = f"{CATALOG}.{SCHEMA}.bronze_edgar_raw"
VOLUME_ROOT = f"/Volumes/{CATALOG}/{SCHEMA}/bronze_edgar_raw"
INGESTED_AT = dt.datetime.utcnow().isoformat()

spark.sql(f"CREATE SCHEMA IF NOT EXISTS {CATALOG}.{SCHEMA}")
spark.sql(f"CREATE VOLUME IF NOT EXISTS {VOLUME}")
print(f"catalog={CATALOG} schema={SCHEMA} mode={MODE} "
      f"companies={len(COMPANIES)} forms={sorted(FORMS)}")

# COMMAND ----------

# DBTITLE 1,What's already ingested
def _table_exists(name: str) -> bool:
    return spark.catalog.tableExists(f"{CATALOG}.{SCHEMA}.{name}")


if _table_exists("bronze_filings"):
    seen_accessions = {
        r["accession"]
        for r in spark.table(f"{CATALOG}.{SCHEMA}.bronze_filings")
        .select("accession")
        .collect()
    }
else:
    seen_accessions = set()

print(f"{len(seen_accessions):,} filings already in bronze_filings"
      f"{' — ignored (mode=full)' if FULL else ''}")

# COMMAND ----------

# DBTITLE 1,Fetch (driver-sequential, rate-limited) — flushes to Delta every batch
client = SecClient(user_agent=USER_AGENT, requests_per_second=8.0)

submission_rows, filing_rows, document_rows, facts_rows, text_rows = [], [], [], [], []
skipped = 0
merged = {}
_i = 0
_t_start = dt.datetime.utcnow()


def _upsert(rows, table, keys, refresh_on_match):
    """MERGE `rows` into `table` on `keys`. refresh_on_match=True overwrites the
    stored row (dimensions re-pulled every run); False keeps the first scraping
    (immutable raw filing data). Creates the table on first run."""
    fq = f"{CATALOG}.{SCHEMA}.{table}"
    if not rows:
        return 0
    df = spark.createDataFrame(rows)
    if not spark.catalog.tableExists(fq):
        df.write.format("delta").option("mergeSchema", "true").saveAsTable(fq)
        return len(rows)
    view = f"_stg_{table}"
    df.createOrReplaceTempView(view)
    on = " AND ".join(f"t.{k} = s.{k}" for k in keys)
    matched = "WHEN MATCHED THEN UPDATE SET *\n" if refresh_on_match else ""
    spark.sql(
        f"MERGE INTO {fq} t USING {view} s ON {on}\n{matched}WHEN NOT MATCHED THEN INSERT *"
    )
    return len(rows)


def _flush():
    """Write everything accumulated so far, then clear the buffers. Called every
    BATCH_SIZE companies and once at the end — a timeout mid-run only loses the
    current batch; the next run resumes from bronze_filings."""
    global submission_rows, filing_rows, document_rows, facts_rows, text_rows
    plan = [
        (submission_rows, "bronze_company_submissions", ["cik"], True),
        (facts_rows, "bronze_xbrl_facts", ["cik"], True),
        (filing_rows, "bronze_filings", ["cik", "accession"], False),
        (document_rows, "bronze_filing_documents", ["cik", "accession", "document"], False),
        (text_rows, "bronze_filing_text", ["cik", "accession", "doc_kind"], False),
    ]
    for rows, table, keys, refresh in plan:
        n = _upsert(rows, table, keys, refresh)
        merged[table] = merged.get(table, 0) + n
    n_new = len(filing_rows)
    submission_rows, filing_rows, document_rows, facts_rows, text_rows = [], [], [], [], []
    if n_new:
        print(f"  [flush] +{n_new} filings written to Delta  "
              f"(cumulative this run: {merged.get('bronze_filings', 0)})")

for _i, co in enumerate(COMPANIES, 1):
    cik_raw, ticker, name = co["cik"], co.get("ticker"), co.get("name")
    c10 = cik10(cik_raw)
    if _i % 25 == 0 or _i == 1:
        _el = (dt.datetime.utcnow() - _t_start).total_seconds()
        print(f"\n--- {_i}/{len(COMPANIES)} companies  ({_el/60:.1f} min elapsed, "
              f"{len(filing_rows)} new filings, {skipped} skipped) ---")
    print(f"=== {ticker or ''} CIK {c10} ({name}) ===")

    try:
        subs = client.submissions(c10)
    except Exception as exc:
        print(f"  submissions failed, skipping CIK: {exc}")
        continue
    submission_rows.append(
        {
            "cik": c10,
            "entity_name": subs.get("name"),
            "ticker": ticker,
            "sic": subs.get("sic"),
            "sic_description": subs.get("sicDescription"),
            "fiscal_year_end": subs.get("fiscalYearEnd"),
            "exchanges": ",".join(subs.get("exchanges", []) or []),
            "tickers": ",".join(subs.get("tickers", []) or []),
            "raw_json": json.dumps(subs)[:15_000_000],
            "ingested_at": INGESTED_AT,
        }
    )

    # companyfacts — the pre-extracted XBRL financial facts (refreshed every run)
    try:
        facts = client.company_facts(c10)
        facts_rows.append(
            {
                "cik": c10,
                "entity_name": facts.get("entityName"),
                "companyfacts_json": json.dumps(facts),
                "ingested_at": INGESTED_AT,
            }
        )
        n_units = sum(
            len(u)
            for t in (facts.get("facts") or {}).values()
            for b in t.values()
            for u in (b.get("units") or {}).values()
        )
        print(f"  companyfacts observations ~ {n_units:,}")
    except Exception as exc:  # some CIKs have no companyfacts
        print(f"  companyfacts unavailable: {exc}")

    # filings — newest first; take up to MAX_NEW that we haven't ingested yet
    new_here = 0
    for f in iter_recent_filings(subs):
        if f.get("form") not in FORMS:
            continue
        accession = f.get("accessionNumber")
        already = accession in seen_accessions
        accn_nd = accession_nodash(accession)
        vol_dir = f"{VOLUME_ROOT}/{c10}/{accn_nd}"
        primary = f.get("primaryDocument") or ""
        primary_path = f"{vol_dir}/{primary}" if primary else ""
        txt_path = f"{vol_dir}/{accn_nd}.txt"

        files_present = (
            (not primary or os.path.exists(primary_path))
            and os.path.exists(txt_path)
        )
        if already and files_present and not FULL:
            skipped += 1
            continue
        if not already:
            if new_here >= MAX_NEW:
                break
            new_here += 1

        filing_rows.append(
            {
                "cik": c10,
                "accession": accession,
                "form": f.get("form"),
                "filing_date": f.get("filingDate"),
                "report_date": f.get("reportDate") or None,
                "primary_document": primary,
                "primary_doc_description": f.get("primaryDocDescription"),
                "is_xbrl": int(f.get("isXBRL") or 0),
                "size": int(f.get("size") or 0),
                "ingested_at": INGESTED_AT,
            }
        )
        os.makedirs(vol_dir, exist_ok=True)

        # primary HTML document -> Volume + text
        if primary and (FULL or not os.path.exists(primary_path)):
            try:
                raw = client.filing_document(c10, accession, primary)
                ext = primary.rsplit(".", 1)[-1].lower() if "." in primary else "bin"
                with open(primary_path, "wb") as out:
                    out.write(raw)
                document_rows.append(
                    {
                        "cik": c10,
                        "accession": accession,
                        "document": primary,
                        "source_format": ext,
                        "volume_path": primary_path,
                        "byte_size": len(raw),
                        "ingested_at": INGESTED_AT,
                    }
                )
                if ext in ("htm", "html", "txt"):
                    body = raw.decode("utf-8", errors="replace")
                    text_rows.append(
                        {
                            "cik": c10,
                            "accession": accession,
                            "doc_kind": "primary_html",
                            "document": primary,
                            "text": body,
                            "char_len": len(body),
                            "ingested_at": INGESTED_AT,
                        }
                    )
            except Exception as exc:
                print(f"  [{accession}] primary doc failed: {exc}")

        # full submission text file (Variety: mixed structured + unstructured)
        if FULL or not os.path.exists(txt_path):
            try:
                sub_txt = client.submission_txt(c10, accession)
                with open(txt_path, "wb") as out:
                    out.write(sub_txt)
                body = sub_txt.decode("utf-8", errors="replace")
                text_rows.append(
                    {
                        "cik": c10,
                        "accession": accession,
                        "doc_kind": "submission_txt",
                        "document": f"{accn_nd}.txt",
                        "text": body[:8_000_000],
                        "char_len": len(body),
                        "ingested_at": INGESTED_AT,
                    }
                )
            except Exception as exc:
                print(f"  [{accession}] submission .txt failed: {exc}")

    print(f"  {new_here} new filing(s)")

    if _i % BATCH_SIZE == 0:
        _flush()

# final flush for the last partial batch
_flush()
print(
    f"\ndone: {_i}/{len(COMPANIES)} companies, {skipped} already-ingested skipped, "
    f"rows written this run: {merged}"
)

# COMMAND ----------

# DBTITLE 1,Exit
dbutils.notebook.exit(
    json.dumps(
        {
            "status": "ok",
            "mode": MODE,
            "new_rows": merged,
            "skipped_existing": skipped,
            "ingested_at": INGESTED_AT,
        }
    )
)
